syntax = "proto3";

package rlmesh.spaces.v1;

import "rlmesh/spaces/v1/types.proto";

// ================================== //
// ======= Fundamental Spaces ======= //
// ================================== //
message BoxSpec {
  oneof bounds {
    bool unbounded = 1;
    UniformBounds uniform = 2;
    ElementwiseBounds elementwise = 3;
  }
}

message UniformBounds {
  bytes low = 1; // one scalar, space dtype, little-endian
  bytes high = 2; // one scalar, space dtype, little-endian
}

message ElementwiseBounds {
  bytes low = 1; // numel scalars, space dtype, little-endian
  bytes high = 2; // numel scalars, space dtype, little-endian
}

message DiscreteSpec {
  int64 n = 1;
  int64 start = 2;
}

message MultiBinarySpec {}

message MultiDiscreteSpec {
  repeated int64 nvec = 1;
}

message TextSpec {
  int64 min_length = 1;
  int64 max_length = 2;
  string charset = 3;
}

// ================================== //
// ======== Composite Spaces ======== //
// ================================== //
message DictSpec {
  repeated string keys = 1;
  repeated SpaceSpec spaces = 2;
}

message TupleSpec {
  repeated SpaceSpec spaces = 1;
}

// ================================== //

message SpaceSpec {
  repeated int64 shape = 1;
  DataType dtype = 2;

  oneof spec {
    // === Fundamental Spaces === //
    BoxSpec box = 10;
    DiscreteSpec discrete = 11;
    MultiBinarySpec multi_binary = 12;
    MultiDiscreteSpec multi_discrete = 13;
    TextSpec text = 14;

    // === Composite Spaces === //
    DictSpec dict = 20;
    TupleSpec tuple = 21;
  }
}
